-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Dell Inc. DELL S2421HS GZD9T83",
  mode = "1920x1080@74.97",
  position = "2611x-236",
  scale = 1,
  transform = 3,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited LEN C32q-20 0x36583638",
  mode = "2560x1440@74.78",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:Lenovo Group Limited LEN C32q-20 0x36583638", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Lenovo Group Limited LEN C32q-20 0x36583638", default = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Lenovo Group Limited LEN C32q-20 0x36583638" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL S2421HS GZD9T83", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL S2421HS GZD9T83" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL S2421HS GZD9T83" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Lenovo Group Limited LEN C32q-20 0x36583638" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Lenovo Group Limited LEN C32q-20 0x36583638" })
hl.workspace_rule({ workspace = "9", monitor = "desc:Lenovo Group Limited LEN C32q-20 0x36583638" })
hl.workspace_rule({ workspace = "10", monitor = "desc:Dell Inc. DELL S2421HS GZD9T83" })
